name: Build the action

on: 
  pull_request: 

  workflow_dispatch:

# Declare default GITHUB_TOKEN permissions as read only.
permissions: read-all
    
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Compile with NPM
        run: |
          npm ci
          npm run all
      
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@f6fff72a3217f580d5afd49a46826795305b63c7 # v3.0.8

  update-dist:
    runs-on: ubuntu-latest
    needs: [build, dependency-check]
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:    
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Compile with NPM
        run: |
          npm ci
          npm run all

      - name: Commit changes if any
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
            echo "Found changes to commit"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"

            git add dist/
            git commit -m "Update dist folder"
            git push
          fi



